Models/TeamMember.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebFrontToBack.Models
{
    public class TeamMember
    {
        public int Id { get; set; }
        [Required,MinLength(6)]
        public string Fullname { get; set; }
        [Required]
        public string Profession { get; set; }
        [Required]
        public string Imagepath { get; set; }
    }
}

Areas/Admin/Controllers/TeamMemberController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebFrontToBack.Areas.Admin.ViewModels;
using WebFrontToBack.DAL;
using WebFrontToBack.Models;
using WebFrontToBack.Utilities.Extensions;

namespace WebFrontToBack.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class TeamMemberController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _webhostenvironment; //Bundan biz projenin locaationlarini tuta bilerik
        public TeamMemberController(AppDbContext context, IWebHostEnvironment webhostenvironment)
        {
            _context = context;
            _webhostenvironment = webhostenvironment;
        }

        public async Task<IActionResult> Index()
        {
            ICollection<TeamMember> members = await _context.TeamMembers.ToListAsync();
            return View(members);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateTeamMemberVM team)
        {
            if (!ModelState.IsValid)
            {
                return View(team);
            }
            if (!team.Photo.CheckContentType("image/"))
            {
                ModelState.AddModelError("Photo", $"Pleas select an image file!Your file:{team.Photo.FileName}");
                return View(); 
            }
            if (!team.Photo.CheckContentSize(200))
            {
                ModelState.AddModelError("Photo", $"Please select an image lesser than 200kb!Your file's size:{team.Photo.Length / 1024}Kb");
                return View();
            }
            string root =Path.Combine(_webhostenvironment.WebRootPath,"assets","img");  //WebRootPath ile biz wwwroot un yerin tuturuq
            string fileName = await team.Photo.SaveAsync(root);

            TeamMember teamMember = new TeamMember()
            {
                Fullname = team.Fullname,
                Imagepath = fileName,
                Profession = team.Profession,
            };
            await _context.TeamMembers.AddAsync(teamMember);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int id)
        {
            TeamMember member = await _context.TeamMembers.FindAsync(id);
            if (member != null)
            {
                string photoPath = Path.Combine
                    (_webhostenvironment.WebRootPath,"assets","img",member.Imagepath);
                if (System.IO.File.Exists(photoPath))
                {
                    System.IO.File.Delete(photoPath);
                }
                _context.TeamMembers.Remove(member);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            TeamMember member = await _context.TeamMembers.FindAsync(id);
            if (member != null)
            {
                return View(member);
            }
            TempData["teamexist"] = "Team member does not exist!";
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(TeamMember member)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            TeamMember? old = await _context.TeamMembers.FindAsync(member.Id);
            if (old != null)
            {
                old.Fullname = member.Fullname;
                old.Profession = member.Profession;
                old.Imagepath = member.Imagepath;
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return Content("There is not any data!");
        }
    }
}

Areas/Admin/Views/TeamMember/Create.cshtml
@{
    ViewData["Title"] = "Create";
}
@model CreateTeamMemberVM
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Team member</h4>
                <form class="forms-sample" method="post" action="create" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="Fullname">Full Name</label>
                        <input asp-for=Fullname type="text" class="form-control" placeholder="Full Name">
                        <span asp-validation-for="Fullname" class="text text-danger"></span>
                        <label asp-for="Profession">Profession</label>     
                        <input asp-for="Profession" type="text" class="form-control" placeholder="Profession"/>
                        <span asp-validation-for="Profession" class="text text-danger"></span>
                        <label asp-for="Photo">Photo</label>
                        <input asp-for="Photo" class="form-control"/>
                        <span asp-validation-for="Photo" class="text text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-primary me-2" asp-area="Admin" asp-controller="TeamMember" asp-action="Create">Add</button>
                    <a onclick="javascript:window.history.back();" class="btn btn-light">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/TeamMember/Index.cshtml
@{
    ViewData["Title"] = "Index";
    int a = 1;
}

@model ICollection<TeamMember>
    @if (TempData["teamexist"] != null)
    {
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>Hi!</strong> @TempData["teamexist"].
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    }
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 style="display:inline;" class="card-title">Team Members</h4>
            <div class="table-responsive">
                <a class="btn btn-success text-light" asp-area="Admin" asp-controller="TeamMember" asp-action="Create" style="float:right;">Create a new team member</a>
                <br />
                <br />
                <br />
                <table class="table table-striped text-center table-bordered">
                    <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>
                                Picture
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                Profession
                            </th>
                            <th>
                                Edit
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (TeamMember member in Model)
                        {
                            <tr>
                                <th>
                                    @a
                                </th>
                                <td class="py-1">
                                    <img src="~/assets/img/@member.Imagepath" alt="image" />
                                </td>
                                <td>
                                    @member.Fullname
                                </td>
                                <td>
                                    @member.Profession
                                </td>
                                <td>
                                    <div class="dropdown">
                                        <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                                            <i class="bx bx-dots-vertical-rounded"></i>
                                        </button>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item" asp-controller="TeamMember" asp-action="Detail" asp-route-id="@member.Id" asp-area="Admin"><i class="mdi mdi-account-card-details"></i> Detail</a>
                                            <a class="dropdown-item" asp-controller="TeamMember" asp-action="Update" asp-route-id="@member.Id" asp-area="Admin"><i class="mdi mdi-refresh"></i> Update</a>
                                            <a class="dropdown-item" asp-controller="TeamMember" asp-action="Delete" asp-route-id="@member.Id" asp-area="Admin"><i class="mdi mdi-delete"></i> Delete</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            a++;
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/TeamMember/Update.cshtml
@{
    ViewData["Title"] = "Update";
}
@model TeamMember
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Team member</h4>
                <form class="forms-sample" method="post" action="update" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="Fullname">Full Name</label>
                        <input asp-for=Fullname type="text" class="form-control" placeholder="Full Name">
                        <span asp-validation-for="Fullname" class="text text-danger"></span>
                        <label asp-for="Profession">Profession</label>
                        <input asp-for="Profession" type="text" class="form-control" placeholder="Profession" />
                        <span asp-validation-for="Profession" class="text text-danger"></span>
                        <label asp-for="Imagepath">Picture</label>
                        <input asp-for="Imagepath" type="text" class="form-control" />
                        <span asp-validation-for="Imagepath" class="text text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-primary me-2" asp-area="Admin" asp-controller="TeamMember" asp-action="Update">Update</button>
                    <a onclick="javascript:window.history.back();" class="btn btn-light">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>