Controllers/BasketController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Reflection.Metadata;
using WebFrontToBack.DAL;
using WebFrontToBack.ViewModel;

namespace WebFrontToBack.Controllers
{
    public class BasketController : Controller
    {
        private const string COOKIES_BASKET = "basketVM";
        private readonly AppDbContext _context;

        public BasketController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            List<BasketItemVM> basketItemVMs = new List<BasketItemVM>();
            List<BasketVM> basketVMs;
            if (Request.Cookies[COOKIES_BASKET] != null)
            {
                basketVMs=JsonConvert.DeserializeObject<List<BasketVM>>(Request.Cookies[COOKIES_BASKET]);
            }
            else
            {
                basketVMs = new List<BasketVM>();
            }
            foreach (var item in basketVMs)
            {
                BasketItemVM basketItemVM = _context.Services
                                                    .Where(s => !s.IsDeleted && s.Id == item.ServiceId)
                                                    .Include(s => s.Category)
                                                    .Include(s => s.ServiceImages)
                                                    .Select(s => new BasketItemVM
                                                    {
                                                        Name = s.Name,
                                                        Id = s.Id,
                                                        CategoryName = s.Category.Name,
                                                        IsDeleted = s.IsDeleted,
                                                        Price = s.Price,
                                                        ServiceCount = item.Count,
                                                        ImagePath = s.ServiceImages.FirstOrDefault(i=>i.IsActive).Path
                                                    }).FirstOrDefault();
                basketItemVMs.Add(basketItemVM);
            }
            return View(basketItemVMs);
        }
        public IActionResult AddBasket(int id,string? ReturnUrl)
        {


            List<BasketVM> basketVMList;
            if (Request.Cookies[COOKIES_BASKET] != null)
            {
                basketVMList = JsonConvert.DeserializeObject<List<BasketVM>>(Request.Cookies[COOKIES_BASKET]);
            }
            else
            {
                basketVMList = new List<BasketVM>();
            }

            BasketVM oldbasket = basketVMList.Where(x => x.ServiceId == id).FirstOrDefault();
            if (oldbasket!=null)
            {
                oldbasket.Count++;
            }
            else
            {
                BasketVM basketVM = new BasketVM()
                {
                    ServiceId = id,
                    Count = 1
                };
                basketVMList.Add(basketVM);
            }
            Response.Cookies.Append(COOKIES_BASKET,JsonConvert.SerializeObject(basketVMList),new CookieOptions
            {
                MaxAge = TimeSpan.FromDays(30)
            });
            if (Url.IsLocalUrl(ReturnUrl) && ReturnUrl != "/Services/LoadMore")
            {
                return Redirect(ReturnUrl);
            }
            return RedirectToAction("Index", "Services");
        }
    }
}
 

ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebFrontToBack.Services;

namespace WebFrontToBack.ViewComponents
{
    public class FooterViewComponent:ViewComponent
    {
        private readonly LayoutService _layoutService;

        public FooterViewComponent(LayoutService layoutService)
        {
            _layoutService = layoutService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await _layoutService.GetSettings());
        }
    }
}

ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebFrontToBack.Services;

namespace WebFrontToBack.ViewComponents
{
    public class HeaderViewComponent:ViewComponent
    {
        private readonly LayoutService _layoutService;

        public HeaderViewComponent(LayoutService layoutService)
        {
            _layoutService = layoutService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await _layoutService.GetSettings());
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"]</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="~/assets/img/apple-icon.png">
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/img/favicon.ico">
    <!-- Load Require CSS -->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font CSS -->
    <link href="~/assets/css/boxicon.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet">
    <!-- Load Tempalte CSS -->
    <link rel="stylesheet" href="~/assets/css/templatemo.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/assets/css/custom.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <!--
    TemplateMo 561 Purple Buzz
    -->
</head>
<body>
    <!-- Header -->
    @await Component.InvokeAsync("Header")
    <!-- Close Header -->
    @RenderBody()
    <!-- Start Footer -->
    @await Component.InvokeAsync("Footer")
    <!-- End Footer -->
    <!-- Bootstrap -->
    <script src="~/assets/js/bootstrap.bundle.min.js"></script>
    <!-- Load jQuery require for isotope -->
    <script src="~/assets/js/jquery.min.js"></script>
    <!-- Isotope -->
    <script src="~/assets/js/isotope.pkgd.js"></script>
    <!-- Page Script -->
    <script>
        $(window).load(function () {
            // init Isotope
            var $projects = $('.projects').isotope({
                itemSelector: '.project',
                layoutMode: 'fitRows'
            });
            $(".filter-btn").click(function () {
                var data_filter = $(this).attr("data-filter");
                $projects.isotope({
                    filter: data_filter
                });
                $(".filter-btn").removeClass("active");
                $(".filter-btn").removeClass("shadow");
                $(this).addClass("active");
                $(this).addClass("shadow");
                return false;
            });
        });
    </script>
    <!-- Templatemo -->
    <script src="~/assets/js/templatemo.js"></script>
    <!-- Custom -->
    <script src="~/assets/js/custom.js"></script>
</body>
</html>

Views/Shared/_ServicesPartialView.cshtml
@model List<Service>
@foreach (Service service in Model)
{
    <div style="padding:5px;" class="col-xl-3 col-md-4 col-sm-6 project @service.Category.Name.ToLower().Trim()">
        <a href="#" class="service-work card border-0 text-white shadow-sm overflow-hidden mx-5 m-sm-0">
            <img class="service card-img" src="~/assets/img/@service.ServiceImages.Where(iz=>iz.IsActive).FirstOrDefault().Path" alt="Card image">
            <div class="service-work-vertical card-img-overlay d-flex align-items-end">
                <div class="service-work-content text-left text-light">
                    <span class="btn btn-outline-light rounded-pill mb-lg-3 px-lg-4 light-300">@service.Name</span>
                    <p class="card-text">
                        @if (service.Description.Length > 25)
                        {
                            @service.Description.Substring(0,25)
                        }
                        else
                        {
                            @service.Description
                        }
                    </p>
                </div>
            </div>
        </a>
        <div class="card-footer text-center">
            <a class="btn btn-outline-primary" asp-controller="Basket" asp-action="AddBasket" asp-route-id="@service.Id" asp-route-ReturnUrl="@Context.Request.Path.Value"><i class="bx bx-cart bx-sm text-dark"></i></a>
        </div>
    </div>
}