Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebFrontToBack.DAL;
using WebFrontToBack.Models;

namespace WebFrontToBack.Controllers
{
    public class AboutController : Controller
    {
        private readonly AppDbContext _context;
        public AboutController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            ICollection<TeamMember> members = await _context.TeamMembers.ToListAsync();
            return View(members);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(TeamMember member)
        {
            return View();
        }
    }
}

Controllers/BasketController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Reflection.Metadata;
using WebFrontToBack.DAL;
using WebFrontToBack.ViewModel;

namespace WebFrontToBack.Controllers
{
    public class BasketController : Controller
    {
        private const string COOKIES_BASKET = "basketVM";
        private readonly AppDbContext _context;

        public BasketController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            List<BasketItemVM> basketItemVMs = new List<BasketItemVM>();
            List<BasketVM> basketVMs;
            if (Request.Cookies[COOKIES_BASKET] != null)
            {
                basketVMs=JsonConvert.DeserializeObject<List<BasketVM>>(Request.Cookies[COOKIES_BASKET]);
            }
            else
            {
                basketVMs = new List<BasketVM>();
            }
            foreach (var item in basketVMs)
            {
                BasketItemVM basketItemVM = _context.Services
                                                    .Where(s => !s.IsDeleted && s.Id == item.ServiceId)
                                                    .Include(s => s.Category)
                                                    .Include(s => s.ServiceImages)
                                                    .Select(s => new BasketItemVM
                                                    {
                                                        Name = s.Name,
                                                        Id = s.Id,
                                                        CategoryName = s.Category.Name,
                                                        IsDeleted = s.IsDeleted,
                                                        Price = s.Price,
                                                        ServiceCount = item.Count,
                                                        ImagePath = s.ServiceImages.FirstOrDefault(i=>i.IsActive).Path
                                                    }).FirstOrDefault();
                basketItemVMs.Add(basketItemVM);
            }
            return View(basketItemVMs);
        }
        public IActionResult AddBasket(int id,string? ReturnUrl)
        {


            List<BasketVM> basketVMList;
            if (Request.Cookies[COOKIES_BASKET] != null)
            {
                basketVMList = JsonConvert.DeserializeObject<List<BasketVM>>(Request.Cookies[COOKIES_BASKET]);
            }
            else
            {
                basketVMList = new List<BasketVM>();
            }

            BasketVM oldbasket = basketVMList.Where(x => x.ServiceId == id).FirstOrDefault();
            if (oldbasket!=null)
            {
                oldbasket.Count++;
            }
            else
            {
                BasketVM basketVM = new BasketVM()
                {
                    ServiceId = id,
                    Count = 1
                };
                basketVMList.Add(basketVM);
            }
            Response.Cookies.Append(COOKIES_BASKET,JsonConvert.SerializeObject(basketVMList),new CookieOptions
            {
                MaxAge = TimeSpan.FromDays(30)
            });
            if (Url.IsLocalUrl(ReturnUrl) && ReturnUrl != "/Services/LoadMore")
            {
                return Redirect(ReturnUrl);
            }
            return RedirectToAction("Index", "Services");
        }
    }
}
 

Views/Shared/Components/Header/Default.cshtml
    @model Dictionary<string,string>;
<nav id="main_nav" class="navbar navbar-expand-lg navbar-light bg-white shadow">
    <div class="container d-flex justify-content-between align-items-center">
        <a class="navbar-brand h1" asp-action="Index" asp-controller="Home">
            @Html.Raw(Model["headerlogo"])
        </a>
        <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-toggler-success" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between" id="navbar-toggler-success">
            <div class="flex-fill mx-xl-5 mb-2">
                <ul class="nav navbar-nav d-flex justify-content-between mx-xl-5 text-center text-dark">
                    <li class="nav-item">
                        <a class="nav-link btn-outline-primary rounded-pill px-3" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn-outline-primary rounded-pill px-3" asp-controller="About" asp-action="Index">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn-outline-primary rounded-pill px-3" asp-controller="Services" asp-action="Index">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn-outline-primary rounded-pill px-3" href="pricing.html">Pricing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn-outline-primary rounded-pill px-3" href="contact.html">Contact</a>
                    </li>
                </ul>
            </div>
            <div class="navbar align-self-center d-flex">
                <a class="nav-link" href="#"><i class='bx bx-bell bx-sm bx-tada-hover text-primary'></i></a>
                <a class="nav-link" href="#"><i class='bx bx-cog bx-sm text-primary'></i></a>
                <a class="nav-link" asp-controller="Basket" asp-action="Index"><i class="bx bx-cart bx-sm text-primary"></i></a>
                <a class="nav-link" href="#">
                    @*<i class='bx bx-user-circle bx-sm text-primary'></i>*@
                    @if (User.Identity.IsAuthenticated)
                    {
                        @User.Identity.Name
                        <a class="nav-link" asp-controller="Account" asp-route-ReturnUrl="@Context.Request.Path.Value" asp-action="Logout">
                            <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0z" />
                                <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z" />
                            </svg>
                        </a>
                    }
                    else
                    {
                        <a class="nav-link" asp-controller="Account" asp-action="Login" asp-route-ReturnUrl="@Context.Request.Path.Value">
                            <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0z" />
                                <path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z" />
                            </svg>
                        </a>
                    }
                </a>
            </div>
        </div>
    </div>
</nav>